version: '3.7'
services:
  minio1:
    image: minio/minio
    container_name: minio1
    hostname: minio1
    networks:
      minio_net:
        aliases:
          - minio1
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /home/pc1/Documents/Projects/minio_data1:/data
    command: server http://minio{1...4}/data

  minio2:
    image: minio/minio
    container_name: minio2
    hostname: minio2
    networks:
      minio_net:
        aliases:
          - minio2
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /home/pc1/Documents/Projects/minio_data2:/data
    command: server http://minio{1...4}/data

  minio3:
    image: minio/minio
    container_name: minio3
    hostname: minio3
    networks:
      minio_net:
        aliases:
          - minio3
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /home/pc1/Documents/Projects/minio_data3:/data
    command: server http://minio{1...4}/data

  minio4:
    image: minio/minio
    container_name: minio4
    hostname: minio4
    networks:
      minio_net:
        aliases:
          - minio4
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /home/pc1/Documents/Projects/minio_data4:/data
    command: server http://minio{1...4}/data

networks:
  minio_net:
    driver: bridge